"""align_nhost_with_final_models

Revision ID: 0d0ab1312ebf
Revises: 20260324_merge_heads_voice_notes
Create Date: 2026-03-31 19:01:05.207774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d0ab1312ebf'
down_revision: Union[str, Sequence[str], None] = '20260324_merge_heads_voice_notes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(length=200), nullable=False),
    sa.Column('teacher_name', sa.String(length=200), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('location_radius_meters', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('recording_session_id', sa.String(length=36), nullable=True),
    sa.Column('extracted_from_message', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('notification_sent_5min', sa.Boolean(), nullable=True),
    sa.Column('notification_sent_1min', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recording_session_id'], ['recording_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_recordings_id'), 'scheduled_recordings', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_recordings_scheduled_at'), 'scheduled_recordings', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduled_recordings_status'), 'scheduled_recordings', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_recordings_user_id'), 'scheduled_recordings', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('referrer_id', sa.String(), nullable=False),
    sa.Column('referred_id', sa.String(), nullable=True),
    sa.Column('referred_email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'EXPIRED', name='referralstatus'), nullable=True),
    sa.Column('bonus_granted', sa.Boolean(), nullable=True),
    sa.Column('bonus_days', sa.Integer(), nullable=True),
    sa.Column('referral_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('transcript_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp_seconds', sa.Integer(), nullable=True),
    sa.Column('t_start_ms', sa.Integer(), nullable=True),
    sa.Column('t_end_ms', sa.Integer(), nullable=True),
    sa.Column('relevance_label', sa.String(length=16), nullable=True),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('relevance_signals', sa.JSON(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['recording_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_chunks_id'), 'transcript_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_transcript_chunks_session_id'), 'transcript_chunks', ['session_id'], unique=False)
    op.create_index(op.f('ix_transcript_chunks_user_id'), 'transcript_chunks', ['user_id'], unique=False)
    op.create_table('user_context',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('current_location_lat', sa.Float(), nullable=True),
    sa.Column('current_location_lng', sa.Float(), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('device_battery_level', sa.Integer(), nullable=True),
    sa.Column('device_platform', sa.String(length=20), nullable=True),
    sa.Column('last_device_ping', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_recording', sa.Boolean(), nullable=True),
    sa.Column('current_recording_id', sa.String(length=36), nullable=True),
    sa.Column('auto_recording_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferred_notification_time', sa.Integer(), nullable=True),
    sa.Column('daily_auto_recordings_count', sa.Integer(), nullable=True),
    sa.Column('daily_auto_recordings_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_document_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_on_device', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_on_device', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('related_class', sa.String(length=200), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('is_deleted_on_device', sa.Boolean(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_document_index_device_id'), 'user_document_index', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_document_index_id'), 'user_document_index', ['id'], unique=False)
    op.create_index(op.f('ix_user_document_index_user_id'), 'user_document_index', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.drop_index('idx_agenda_chunks_relevance_label', table_name='agenda_chunks')
    op.drop_index('idx_agenda_chunks_session_id', table_name='agenda_chunks')
    op.drop_index('idx_agenda_chunks_user_id', table_name='agenda_chunks')
    op.drop_table('agenda_chunks')
    op.drop_index('ix_learning_patterns_id', table_name='learning_patterns')
    op.drop_table('learning_patterns')
    op.drop_index('idx_history_conv_user', table_name='history')
    op.drop_table('history')
    op.drop_table('conversations')
    op.drop_index('ix_personal_agents_agent_id', table_name='personal_agents')
    op.drop_index('ix_personal_agents_id', table_name='personal_agents')
    op.drop_table('personal_agents')
    op.drop_index('idx_agenda_sessions_status', table_name='agenda_sessions')
    op.drop_index('idx_agenda_sessions_user_id', table_name='agenda_sessions')
    op.drop_index('ix_agenda_sessions_user_id', table_name='agenda_sessions')
    op.drop_table('agenda_sessions')
    op.drop_table('media')
    op.drop_index('idx_usage_user_created', table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_table('live_search_logs')
    op.drop_index('ix_agent_interactions_id', table_name='agent_interactions')
    op.drop_index('ix_agent_interactions_interaction_id', table_name='agent_interactions')
    op.drop_table('agent_interactions')
    op.drop_index('idx_sync_checkpoints_user_device', table_name='voice_note_sync_checkpoints')
    op.drop_table('voice_note_sync_checkpoints')
    op.drop_index('idx_voice_note_chunks_voice_note_id', table_name='voice_note_chunks')
    op.drop_table('voice_note_chunks')
    op.drop_index('idx_voice_notes_client_record', table_name='voice_notes')
    op.drop_index('idx_voice_notes_user_created', table_name='voice_notes')
    op.drop_index('idx_voice_notes_user_status', table_name='voice_notes')
    op.drop_index('ix_voice_notes_is_deleted', table_name='voice_notes')
    op.drop_index('ix_voice_notes_status', table_name='voice_notes')
    op.drop_table('voice_notes')
    op.drop_index('idx_agenda_items_session_id', table_name='agenda_items')
    op.drop_index('idx_agenda_items_type', table_name='agenda_items')
    op.drop_index('idx_agenda_items_user_id', table_name='agenda_items')
    op.drop_table('agenda_items')
    op.drop_table('uploaded_files')
    op.drop_index('idx_processing_jobs_idempotent', table_name='voice_note_processing_jobs')
    op.drop_index('idx_processing_jobs_status_queue', table_name='voice_note_processing_jobs')
    op.drop_index('idx_processing_jobs_voice_note_id', table_name='voice_note_processing_jobs')
    op.drop_index('ix_voice_note_processing_jobs_job_type', table_name='voice_note_processing_jobs')
    op.drop_index('ix_voice_note_processing_jobs_status', table_name='voice_note_processing_jobs')
    op.drop_table('voice_note_processing_jobs')
    op.alter_column('chat_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('chat_sessions', 'messages_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint('chat_sessions_user_id_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('device_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('device_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_device_tokens_is_active', table_name='device_tokens')
    op.drop_index('ix_device_tokens_platform', table_name='device_tokens')
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_foreign_key(None, 'group_activities', 'users', ['user_id'], ['id'])
    op.add_column('group_invitations', sa.Column('invited_user_id', sa.String(length=50), nullable=True))
    op.add_column('group_invitations', sa.Column('invited_at', sa.DateTime(), nullable=False))
    op.drop_index('ix_group_invitations_expires_at', table_name='group_invitations')
    op.drop_index('ix_group_invitations_invited_by', table_name='group_invitations')
    op.drop_index('ix_group_invitations_status', table_name='group_invitations')
    op.drop_constraint('uq_invitation_token', 'group_invitations', type_='unique')
    op.drop_index('ix_group_invitations_invitation_token', table_name='group_invitations')
    op.create_index(op.f('ix_group_invitations_invitation_token'), 'group_invitations', ['invitation_token'], unique=True)
    op.create_foreign_key(None, 'group_invitations', 'users', ['invited_by'], ['id'])
    op.create_foreign_key(None, 'group_invitations', 'users', ['invited_user_id'], ['id'])
    op.drop_column('group_invitations', 'accepted_by_user_id')
    op.drop_column('group_invitations', 'created_at')
    op.add_column('group_members', sa.Column('invited_by', sa.String(length=50), nullable=True))
    op.add_column('group_members', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('group_members', sa.Column('messages_count', sa.Integer(), nullable=True))
    op.add_column('group_members', sa.Column('documents_shared', sa.Integer(), nullable=True))
    op.add_column('group_members', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('group_members', sa.Column('muted_until', sa.DateTime(), nullable=True))
    op.drop_index('ix_group_members_role', table_name='group_members')
    op.drop_constraint('uq_group_members', 'group_members', type_='unique')
    op.create_foreign_key(None, 'group_members', 'users', ['invited_by'], ['id'])
    op.create_foreign_key(None, 'group_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('group_members', 'last_active_at')
    op.add_column('group_messages', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('group_messages', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.add_column('group_messages', sa.Column('context', sa.JSON(), nullable=True))
    op.add_column('group_messages', sa.Column('ai_model', sa.String(length=50), nullable=True))
    op.add_column('group_messages', sa.Column('reply_to', sa.String(length=50), nullable=True))
    op.add_column('group_messages', sa.Column('mentioned_users', sa.JSON(), nullable=True))
    op.add_column('group_messages', sa.Column('reactions', sa.JSON(), nullable=True))
    op.drop_index('ix_group_messages_message_type', table_name='group_messages')
    op.drop_index('ix_group_messages_user_id', table_name='group_messages')
    op.create_foreign_key(None, 'group_messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'group_messages', 'group_messages', ['reply_to'], ['id'])
    op.drop_column('group_messages', 'attachments')
    op.drop_column('group_messages', 'message')
    op.drop_column('group_messages', 'ai_context_docs')
    op.add_column('payments', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('gateway_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('gateway_response', sa.JSON(), nullable=True))
    op.add_column('payments', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('payments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'),
               existing_nullable=True)
    op.drop_constraint('payments_payment_id_key', 'payments', type_='unique')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.drop_constraint('payments_user_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_plan_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'subscriptions', ['subscription_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.drop_column('payments', 'payment_id')
    op.drop_column('payments', 'payment_metadata')
    op.drop_column('payments', 'plan_id')
    op.add_column('plans', sa.Column('display_name', sa.String(length=100), nullable=False))
    op.add_column('plans', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('plans', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('plans', sa.Column('requests_per_month', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('max_file_size_mb', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('plans', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('plans', sa.Column('is_demo', sa.Boolean(), nullable=True))
    op.add_column('plans', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('plans', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('plans', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index('idx_plans_name', table_name='plans')
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.drop_column('plans', 'max_voice_minutes')
    op.drop_column('plans', 'demo_requests_per_day')
    op.drop_column('plans', 'max_files')
    op.drop_column('plans', 'demo_storage')
    op.drop_column('plans', 'image_engine')
    op.drop_column('plans', 'max_document_size_mb')
    op.drop_column('plans', 'demo_files')
    op.drop_column('plans', 'max_images')
    op.drop_column('plans', 'max_live_search')
    op.drop_column('plans', 'max_messages')
    op.drop_column('plans', 'gpt_model')
    op.drop_column('plans', 'demo_images')
    op.alter_column('private_ai_messages', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_private_ai_messages_created_at'), 'private_ai_messages', ['created_at'], unique=False)
    op.drop_constraint('private_ai_messages_user_id_fkey', 'private_ai_messages', type_='foreignkey')
    op.create_foreign_key(None, 'private_ai_messages', 'users', ['user_id'], ['id'])
    op.drop_index('idx_recording_sessions_status', table_name='recording_sessions')
    op.drop_index('idx_recording_sessions_user_id', table_name='recording_sessions')
    op.create_index(op.f('ix_recording_sessions_id'), 'recording_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_recording_sessions_status'), 'recording_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_recording_sessions_user_id'), 'recording_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'recording_sessions', 'scheduled_recordings', ['scheduled_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_session_items_item_type', table_name='session_items')
    op.drop_index('idx_session_items_session_id', table_name='session_items')
    op.drop_index('idx_session_items_user_id', table_name='session_items')
    op.create_index(op.f('ix_session_items_id'), 'session_items', ['id'], unique=False)
    op.create_index(op.f('ix_session_items_item_type'), 'session_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_session_items_session_id'), 'session_items', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_items_user_id'), 'session_items', ['user_id'], unique=False)
    op.add_column('shared_documents', sa.Column('file_url', sa.String(length=1000), nullable=True))
    op.add_column('shared_documents', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('shared_documents', sa.Column('views_count', sa.Integer(), nullable=True))
    op.add_column('shared_documents', sa.Column('downloads_count', sa.Integer(), nullable=True))
    op.add_column('shared_documents', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.add_column('shared_documents', sa.Column('can_download', sa.Boolean(), nullable=True))
    op.add_column('shared_documents', sa.Column('can_edit', sa.Boolean(), nullable=True))
    op.add_column('shared_documents', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('shared_documents', sa.Column('ai_key_concepts', sa.JSON(), nullable=True))
    op.alter_column('shared_documents', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('shared_documents', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_shared_documents_document_id', table_name='shared_documents')
    op.drop_index('ix_shared_documents_shared_at', table_name='shared_documents')
    op.drop_index('ix_shared_documents_shared_by', table_name='shared_documents')
    op.drop_constraint('uq_shared_documents', 'shared_documents', type_='unique')
    op.create_foreign_key(None, 'shared_documents', 'users', ['shared_by'], ['id'])
    op.drop_column('shared_documents', 'download_count')
    op.add_column('study_groups', sa.Column('created_by', sa.String(length=50), nullable=False))
    op.add_column('study_groups', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('study_groups', sa.Column('course_code', sa.String(length=50), nullable=True))
    op.add_column('study_groups', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('study_groups', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.add_column('study_groups', sa.Column('ai_enabled', sa.Boolean(), nullable=True))
    op.add_column('study_groups', sa.Column('ai_personality', sa.String(length=50), nullable=True))
    op.add_column('study_groups', sa.Column('documents_count', sa.Integer(), nullable=True))
    op.add_column('study_groups', sa.Column('messages_count', sa.Integer(), nullable=True))
    op.add_column('study_groups', sa.Column('notification_settings', sa.JSON(), nullable=True))
    op.alter_column('study_groups', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('study_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('study_groups', 'max_members',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('study_groups', 'members_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_study_groups_created_at', table_name='study_groups')
    op.drop_index('ix_study_groups_creator_id', table_name='study_groups')
    op.drop_index('ix_study_groups_is_public', table_name='study_groups')
    op.drop_index('ix_study_groups_university', table_name='study_groups')
    op.create_index(op.f('ix_study_groups_is_active'), 'study_groups', ['is_active'], unique=False)
    op.create_index(op.f('ix_study_groups_name'), 'study_groups', ['name'], unique=False)
    op.create_foreign_key(None, 'study_groups', 'users', ['created_by'], ['id'])
    op.drop_column('study_groups', 'is_public')
    op.drop_column('study_groups', 'creator_id')
    op.drop_column('study_groups', 'avatar_url')
    op.add_column('subscriptions', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CANCELLED', 'EXPIRED', 'PENDING', name='subscriptionstatus'), nullable=True))
    op.add_column('subscriptions', sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('subscriptions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('subscriptions', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('subscriptions', sa.Column('gateway', sa.String(length=50), nullable=True))
    op.add_column('subscriptions', sa.Column('gateway_subscription_id', sa.String(length=100), nullable=True))
    op.add_column('subscriptions', sa.Column('payment_metadata', sa.JSON(), nullable=True))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('subscriptions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.drop_constraint('subscriptions_plan_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.drop_column('subscriptions', 'active')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'end_date')
    op.drop_index('ix_user_profiles_user_id', table_name='user_profiles')
    op.create_unique_constraint(None, 'user_profiles', ['user_id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('idx_users_demo_until', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_plan_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint('users_plan_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'provider')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_plan_id_fkey', 'users', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('idx_users_plan_id', 'users', ['plan_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_demo_until', 'users', ['demo_until'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'], unique=True)
    op.add_column('subscriptions', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('subscriptions_plan_id_fkey', 'subscriptions', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'payment_metadata')
    op.drop_column('subscriptions', 'gateway_subscription_id')
    op.drop_column('subscriptions', 'gateway')
    op.drop_column('subscriptions', 'payment_method')
    op.drop_column('subscriptions', 'auto_renew')
    op.drop_column('subscriptions', 'cancelled_at')
    op.drop_column('subscriptions', 'expires_at')
    op.drop_column('subscriptions', 'starts_at')
    op.drop_column('subscriptions', 'status')
    op.add_column('study_groups', sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('study_groups', sa.Column('creator_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('study_groups', sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'study_groups', type_='foreignkey')
    op.drop_index(op.f('ix_study_groups_name'), table_name='study_groups')
    op.drop_index(op.f('ix_study_groups_is_active'), table_name='study_groups')
    op.create_index('ix_study_groups_university', 'study_groups', ['university'], unique=False)
    op.create_index('ix_study_groups_is_public', 'study_groups', ['is_public'], unique=False)
    op.create_index('ix_study_groups_creator_id', 'study_groups', ['creator_id'], unique=False)
    op.create_index('ix_study_groups_created_at', 'study_groups', ['created_at'], unique=False)
    op.alter_column('study_groups', 'members_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('study_groups', 'max_members',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('study_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('study_groups', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('study_groups', 'notification_settings')
    op.drop_column('study_groups', 'messages_count')
    op.drop_column('study_groups', 'documents_count')
    op.drop_column('study_groups', 'ai_personality')
    op.drop_column('study_groups', 'ai_enabled')
    op.drop_column('study_groups', 'archived_at')
    op.drop_column('study_groups', 'is_active')
    op.drop_column('study_groups', 'course_code')
    op.drop_column('study_groups', 'is_private')
    op.drop_column('study_groups', 'created_by')
    op.add_column('shared_documents', sa.Column('download_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shared_documents', type_='foreignkey')
    op.create_unique_constraint('uq_shared_documents', 'shared_documents', ['group_id', 'document_id'])
    op.create_index('ix_shared_documents_shared_by', 'shared_documents', ['shared_by'], unique=False)
    op.create_index('ix_shared_documents_shared_at', 'shared_documents', ['shared_at'], unique=False)
    op.create_index('ix_shared_documents_document_id', 'shared_documents', ['document_id'], unique=False)
    op.alter_column('shared_documents', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('shared_documents', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('shared_documents', 'ai_key_concepts')
    op.drop_column('shared_documents', 'ai_summary')
    op.drop_column('shared_documents', 'can_edit')
    op.drop_column('shared_documents', 'can_download')
    op.drop_column('shared_documents', 'comments_count')
    op.drop_column('shared_documents', 'downloads_count')
    op.drop_column('shared_documents', 'views_count')
    op.drop_column('shared_documents', 'category')
    op.drop_column('shared_documents', 'file_url')
    op.drop_index(op.f('ix_session_items_user_id'), table_name='session_items')
    op.drop_index(op.f('ix_session_items_session_id'), table_name='session_items')
    op.drop_index(op.f('ix_session_items_item_type'), table_name='session_items')
    op.drop_index(op.f('ix_session_items_id'), table_name='session_items')
    op.create_index('idx_session_items_user_id', 'session_items', ['user_id'], unique=False)
    op.create_index('idx_session_items_session_id', 'session_items', ['session_id'], unique=False)
    op.create_index('idx_session_items_item_type', 'session_items', ['item_type'], unique=False)
    op.drop_constraint(None, 'recording_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_recording_sessions_user_id'), table_name='recording_sessions')
    op.drop_index(op.f('ix_recording_sessions_status'), table_name='recording_sessions')
    op.drop_index(op.f('ix_recording_sessions_id'), table_name='recording_sessions')
    op.create_index('idx_recording_sessions_user_id', 'recording_sessions', ['user_id'], unique=False)
    op.create_index('idx_recording_sessions_status', 'recording_sessions', ['status'], unique=False)
    op.drop_constraint(None, 'private_ai_messages', type_='foreignkey')
    op.create_foreign_key('private_ai_messages_user_id_fkey', 'private_ai_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_private_ai_messages_created_at'), table_name='private_ai_messages')
    op.alter_column('private_ai_messages', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('plans', sa.Column('demo_images', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('gpt_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('max_messages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('max_live_search', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('max_images', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('demo_files', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('max_document_size_mb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('image_engine', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('demo_storage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('max_files', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('demo_requests_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('max_voice_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.create_index('idx_plans_name', 'plans', ['name'], unique=False)
    op.alter_column('plans', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('plans', 'updated_at')
    op.drop_column('plans', 'created_at')
    op.drop_column('plans', 'sort_order')
    op.drop_column('plans', 'is_demo')
    op.drop_column('plans', 'is_active')
    op.drop_column('plans', 'features')
    op.drop_column('plans', 'max_file_size_mb')
    op.drop_column('plans', 'requests_per_month')
    op.drop_column('plans', 'currency')
    op.drop_column('plans', 'description')
    op.drop_column('plans', 'display_name')
    op.add_column('payments', sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('payment_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('payment_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_plan_id_fkey', 'payments', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('payments_user_id_fkey', 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_unique_constraint('payments_payment_id_key', 'payments', ['payment_id'])
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('payments', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'processed_at')
    op.drop_column('payments', 'gateway_response')
    op.drop_column('payments', 'gateway_transaction_id')
    op.drop_column('payments', 'description')
    op.drop_column('payments', 'subscription_id')
    op.add_column('group_messages', sa.Column('ai_context_docs', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('group_messages', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('group_messages', sa.Column('attachments', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'group_messages', type_='foreignkey')
    op.drop_constraint(None, 'group_messages', type_='foreignkey')
    op.create_index('ix_group_messages_user_id', 'group_messages', ['user_id'], unique=False)
    op.create_index('ix_group_messages_message_type', 'group_messages', ['message_type'], unique=False)
    op.drop_column('group_messages', 'reactions')
    op.drop_column('group_messages', 'mentioned_users')
    op.drop_column('group_messages', 'reply_to')
    op.drop_column('group_messages', 'ai_model')
    op.drop_column('group_messages', 'context')
    op.drop_column('group_messages', 'edited_at')
    op.drop_column('group_messages', 'content')
    op.add_column('group_members', sa.Column('last_active_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_unique_constraint('uq_group_members', 'group_members', ['group_id', 'user_id'])
    op.create_index('ix_group_members_role', 'group_members', ['role'], unique=False)
    op.drop_column('group_members', 'muted_until')
    op.drop_column('group_members', 'is_active')
    op.drop_column('group_members', 'documents_shared')
    op.drop_column('group_members', 'messages_count')
    op.drop_column('group_members', 'last_seen_at')
    op.drop_column('group_members', 'invited_by')
    op.add_column('group_invitations', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('group_invitations', sa.Column('accepted_by_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'group_invitations', type_='foreignkey')
    op.drop_constraint(None, 'group_invitations', type_='foreignkey')
    op.drop_index(op.f('ix_group_invitations_invitation_token'), table_name='group_invitations')
    op.create_index('ix_group_invitations_invitation_token', 'group_invitations', ['invitation_token'], unique=False)
    op.create_unique_constraint('uq_invitation_token', 'group_invitations', ['invitation_token'])
    op.create_index('ix_group_invitations_status', 'group_invitations', ['status'], unique=False)
    op.create_index('ix_group_invitations_invited_by', 'group_invitations', ['invited_by'], unique=False)
    op.create_index('ix_group_invitations_expires_at', 'group_invitations', ['expires_at'], unique=False)
    op.drop_column('group_invitations', 'invited_at')
    op.drop_column('group_invitations', 'invited_user_id')
    op.drop_constraint(None, 'group_activities', type_='foreignkey')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.create_index('ix_device_tokens_platform', 'device_tokens', ['platform'], unique=False)
    op.create_index('ix_device_tokens_is_active', 'device_tokens', ['is_active'], unique=False)
    op.alter_column('device_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('device_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_user_id_fkey', 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chat_sessions', 'messages_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chat_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_table('voice_note_processing_jobs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('voice_note_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('job_type', postgresql.ENUM('transcription', 'summarization', 'extraction', 'full_pipeline', name='processingjobtype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'completed', 'failed', 'retrying', name='processingjobstatus'), server_default=sa.text("'pending'::processingjobstatus"), autoincrement=False, nullable=False),
    sa.Column('audio_checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('params_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('job_params', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('result_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('max_attempts', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue_name', sa.VARCHAR(length=50), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('worker_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['voice_note_id'], ['voice_notes.id'], name='voice_note_processing_jobs_voice_note_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='voice_note_processing_jobs_pkey')
    )
    op.create_index('ix_voice_note_processing_jobs_status', 'voice_note_processing_jobs', ['status'], unique=False)
    op.create_index('ix_voice_note_processing_jobs_job_type', 'voice_note_processing_jobs', ['job_type'], unique=False)
    op.create_index('idx_processing_jobs_voice_note_id', 'voice_note_processing_jobs', ['voice_note_id'], unique=False)
    op.create_index('idx_processing_jobs_status_queue', 'voice_note_processing_jobs', ['status', 'queue_name', 'priority'], unique=False)
    op.create_index('idx_processing_jobs_idempotent', 'voice_note_processing_jobs', ['audio_checksum', 'job_type', 'params_hash'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='uploaded_files_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='uploaded_files_pkey')
    )
    op.create_table('agenda_items',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'suggested'::character varying"), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('datetime_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('datetime_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('important', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=16), server_default=sa.text("'ai'::character varying"), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('item_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['agenda_sessions.id'], name='agenda_items_session_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='agenda_items_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='agenda_items_pkey')
    )
    op.create_index('idx_agenda_items_user_id', 'agenda_items', ['user_id'], unique=False)
    op.create_index('idx_agenda_items_type', 'agenda_items', ['item_type'], unique=False)
    op.create_index('idx_agenda_items_session_id', 'agenda_items', ['session_id'], unique=False)
    op.create_table('voice_notes',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_record_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'es'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'uploading', 'uploaded', 'queued', 'transcribing', 'processing', 'completed', 'error', 'cancelled', name='voicenotestatus'), server_default=sa.text("'draft'::voicenotestatus"), autoincrement=False, nullable=False),
    sa.Column('upload_strategy', postgresql.ENUM('streaming', 'resumable', 'bulk', name='voicenoteuploadstrategy'), server_default=sa.text("'resumable'::voicenoteuploadstrategy"), autoincrement=False, nullable=False),
    sa.Column('total_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_chunks_expected', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_chunks_received', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('audio_format', sa.VARCHAR(length=20), server_default=sa.text("'webm'::character varying"), autoincrement=False, nullable=False),
    sa.Column('sample_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('storage_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('storage_etag', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transcript_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('extracted_items', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('topics', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('entities', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('processing_version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('processing_checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('client_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('upload_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('upload_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processing_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processing_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='voice_notes_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='voice_notes_pkey'),
    sa.UniqueConstraint('client_record_id', name='voice_notes_client_record_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_voice_notes_status', 'voice_notes', ['status'], unique=False)
    op.create_index('ix_voice_notes_is_deleted', 'voice_notes', ['is_deleted'], unique=False)
    op.create_index('idx_voice_notes_user_status', 'voice_notes', ['user_id', 'status'], unique=False)
    op.create_index('idx_voice_notes_user_created', 'voice_notes', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_voice_notes_client_record', 'voice_notes', ['client_record_id'], unique=False)
    op.create_table('voice_note_chunks',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('voice_note_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_chunk_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('byte_offset', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('byte_length', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checksum_sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'received', 'verified', 'failed', name='audiochunkstatus'), server_default=sa.text("'pending'::audiochunkstatus"), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['voice_note_id'], ['voice_notes.id'], name='voice_note_chunks_voice_note_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='voice_note_chunks_pkey'),
    sa.UniqueConstraint('voice_note_id', 'chunk_index', name='idx_voice_note_chunks_note_index')
    )
    op.create_index('idx_voice_note_chunks_voice_note_id', 'voice_note_chunks', ['voice_note_id'], unique=False)
    op.create_table('voice_note_sync_checkpoints',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('client_last_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('client_record_ids', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('server_sync_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('missing_on_server', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('missing_on_client', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('conflicts', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('sync_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('records_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='voice_note_sync_checkpoints_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='voice_note_sync_checkpoints_pkey')
    )
    op.create_index('idx_sync_checkpoints_user_device', 'voice_note_sync_checkpoints', ['user_id', 'device_id', 'created_at'], unique=False)
    op.create_table('agent_interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('interaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agent_response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context_used', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('personalization_applied', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_satisfaction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['personal_agents.agent_id'], name='agent_interactions_agent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agent_interactions_pkey')
    )
    op.create_index('ix_agent_interactions_interaction_id', 'agent_interactions', ['interaction_id'], unique=True)
    op.create_index('ix_agent_interactions_id', 'agent_interactions', ['id'], unique=False)
    op.create_table('live_search_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='live_search_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='live_search_logs_pkey')
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('detail', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='usage_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='usage_logs_pkey')
    )
    op.create_index('idx_usage_user_created', 'usage_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='media_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='media_pkey')
    )
    op.create_table('agenda_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('teacher_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('teacher_email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('topic_hint', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('session_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'recording'::character varying"), autoincrement=False, nullable=False),
    sa.Column('live_transcript', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('extracted_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='agenda_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='agenda_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_agenda_sessions_user_id', 'agenda_sessions', ['user_id'], unique=False)
    op.create_index('idx_agenda_sessions_user_id', 'agenda_sessions', ['user_id'], unique=False)
    op.create_index('idx_agenda_sessions_status', 'agenda_sessions', ['status'], unique=False)
    op.create_table('personal_agents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_type', postgresql.ENUM('tutor', 'mentor', 'assistant', 'coach', 'researcher', 'creative', name='agenttype'), autoincrement=False, nullable=False),
    sa.Column('specialization', postgresql.ENUM('technology', 'business', 'academic', 'creative', 'personal_development', 'language', 'science', name='specialization'), autoincrement=False, nullable=False),
    sa.Column('personality_config', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('response_templates', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('specialized_prompts', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('learned_preferences', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('user_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('conversation_memory', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('interaction_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('effectiveness_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.5'), autoincrement=False, nullable=True),
    sa.Column('adaptation_level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_interaction', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name='personal_agents_user_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='personal_agents_pkey')
    )
    op.create_index('ix_personal_agents_id', 'personal_agents', ['id'], unique=False)
    op.create_index('ix_personal_agents_agent_id', 'personal_agents', ['agent_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('conversations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('metadata_extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='conversations_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='fk_history_conversation_id'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='history_conversation_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='history_pkey')
    )
    op.create_index('idx_history_conv_user', 'history', ['conversation_id', 'user_id'], unique=False)
    op.create_table('learning_patterns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pattern_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pattern_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name='learning_patterns_user_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='learning_patterns_pkey')
    )
    op.create_index('ix_learning_patterns_id', 'learning_patterns', ['id'], unique=False)
    op.create_table('agenda_chunks',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('t_start_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('t_end_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('relevance_label', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('relevance_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relevance_signals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['agenda_sessions.id'], name='agenda_chunks_session_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='agenda_chunks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='agenda_chunks_pkey')
    )
    op.create_index('idx_agenda_chunks_user_id', 'agenda_chunks', ['user_id'], unique=False)
    op.create_index('idx_agenda_chunks_session_id', 'agenda_chunks', ['session_id'], unique=False)
    op.create_index('idx_agenda_chunks_relevance_label', 'agenda_chunks', ['relevance_label'], unique=False)
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_document_index_user_id'), table_name='user_document_index')
    op.drop_index(op.f('ix_user_document_index_id'), table_name='user_document_index')
    op.drop_index(op.f('ix_user_document_index_device_id'), table_name='user_document_index')
    op.drop_table('user_document_index')
    op.drop_table('user_context')
    op.drop_index(op.f('ix_transcript_chunks_user_id'), table_name='transcript_chunks')
    op.drop_index(op.f('ix_transcript_chunks_session_id'), table_name='transcript_chunks')
    op.drop_index(op.f('ix_transcript_chunks_id'), table_name='transcript_chunks')
    op.drop_table('transcript_chunks')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_scheduled_recordings_user_id'), table_name='scheduled_recordings')
    op.drop_index(op.f('ix_scheduled_recordings_status'), table_name='scheduled_recordings')
    op.drop_index(op.f('ix_scheduled_recordings_scheduled_at'), table_name='scheduled_recordings')
    op.drop_index(op.f('ix_scheduled_recordings_id'), table_name='scheduled_recordings')
    op.drop_table('scheduled_recordings')
    # ### end Alembic commands ###
