"""Add demo columns to plans

Revision ID: 4e47f0d46ffb
Revises: cf6310d2d8b0
Create Date: 2025-09-14 14:39:47.330006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e47f0d46ffb'
down_revision: Union[str, Sequence[str], None] = 'cf6310d2d8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE conversations ADD COLUMN IF NOT EXISTS metadata_extra JSON")
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conversations', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.execute("ALTER TABLE conversations DROP COLUMN IF EXISTS extra_metadata")
    op.execute("ALTER TABLE history ADD COLUMN IF NOT EXISTS conversation_id INTEGER")
    op.alter_column('history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("CREATE INDEX IF NOT EXISTS idx_history_conv_user ON history (conversation_id, user_id)")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'fk_history_conversation_id'
            ) THEN
                ALTER TABLE history
                ADD CONSTRAINT fk_history_conversation_id
                FOREIGN KEY (conversation_id) REFERENCES conversations(id);
            END IF;
        END $$;
        """
    )
    op.alter_column('media', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('media', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('media', 'url',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('uploaded_files', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('uploaded_files', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usage_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("CREATE INDEX IF NOT EXISTS idx_usage_user_created ON usage_logs (user_id, created_at)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_usage_user_created', table_name='usage_logs')
    op.alter_column('usage_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('uploaded_files', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('uploaded_files', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('media', 'url',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('media', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('media', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_index('idx_history_conv_user', table_name='history')
    op.alter_column('history', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('history', 'conversation_id')
    op.add_column('conversations', sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('conversations', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('conversations', 'metadata_extra')
    # ### end Alembic commands ###
