"""agregar columna email a users

Revision ID: cf6310d2d8b0
Revises: 
Create Date: 2025-09-09 19:03:49.454907
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf6310d2d8b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_histories_id'), table_name='histories')
    op.drop_table('histories')
    op.alter_column('media', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('media', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('media', 'url',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('media_user_id_fkey'), 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'users', ['user_id'], ['id'])

    # Agregar columna email de forma segura
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # Llenar los valores existentes con un valor temporal
    op.execute("UPDATE users SET email = username || '@example.com' WHERE email IS NULL")
    # Poner la columna como NOT NULL
    op.alter_column('users', 'email', nullable=False)

    op.add_column('users', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'demo_started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_foreign_key(None, 'users', 'plans', ['plan_id'], ['id'])
    op.drop_column('users', 'is_subscribed')
    op.drop_column('users', 'subscription_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_plan', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_subscribed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'demo_started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'plan_id')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key(op.f('media_user_id_fkey'), 'media', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('media', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('media', 'url',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('media', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('media', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('histories_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('histories_pkey'))
    )
    op.create_index(op.f('ix_histories_id'), 'histories', ['id'], unique=False)
    # ### end Alembic commands ###
