# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notes_pb2 as notes__pb2


class NotesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNoteFromAudio = channel.unary_unary(
                '/notes.NotesService/CreateNoteFromAudio',
                request_serializer=notes__pb2.CreateNoteFromAudioRequest.SerializeToString,
                response_deserializer=notes__pb2.CreateNoteResponse.FromString,
                )
        self.CreateNoteFromText = channel.unary_unary(
                '/notes.NotesService/CreateNoteFromText',
                request_serializer=notes__pb2.CreateNoteFromTextRequest.SerializeToString,
                response_deserializer=notes__pb2.CreateNoteResponse.FromString,
                )
        self.GetNote = channel.unary_unary(
                '/notes.NotesService/GetNote',
                request_serializer=notes__pb2.GetNoteRequest.SerializeToString,
                response_deserializer=notes__pb2.GetNoteResponse.FromString,
                )
        self.ListNotes = channel.unary_unary(
                '/notes.NotesService/ListNotes',
                request_serializer=notes__pb2.ListNotesRequest.SerializeToString,
                response_deserializer=notes__pb2.ListNotesResponse.FromString,
                )
        self.ListTasks = channel.unary_unary(
                '/notes.NotesService/ListTasks',
                request_serializer=notes__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=notes__pb2.ListTasksResponse.FromString,
                )
        self.UpdateTask = channel.unary_unary(
                '/notes.NotesService/UpdateTask',
                request_serializer=notes__pb2.UpdateTaskRequest.SerializeToString,
                response_deserializer=notes__pb2.Task.FromString,
                )
        self.SummarizeRange = channel.unary_unary(
                '/notes.NotesService/SummarizeRange',
                request_serializer=notes__pb2.SummarizeRangeRequest.SerializeToString,
                response_deserializer=notes__pb2.SummarizeRangeResponse.FromString,
                )


class NotesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNoteFromAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNoteFromText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNoteFromAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNoteFromAudio,
                    request_deserializer=notes__pb2.CreateNoteFromAudioRequest.FromString,
                    response_serializer=notes__pb2.CreateNoteResponse.SerializeToString,
            ),
            'CreateNoteFromText': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNoteFromText,
                    request_deserializer=notes__pb2.CreateNoteFromTextRequest.FromString,
                    response_serializer=notes__pb2.CreateNoteResponse.SerializeToString,
            ),
            'GetNote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNote,
                    request_deserializer=notes__pb2.GetNoteRequest.FromString,
                    response_serializer=notes__pb2.GetNoteResponse.SerializeToString,
            ),
            'ListNotes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotes,
                    request_deserializer=notes__pb2.ListNotesRequest.FromString,
                    response_serializer=notes__pb2.ListNotesResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=notes__pb2.ListTasksRequest.FromString,
                    response_serializer=notes__pb2.ListTasksResponse.SerializeToString,
            ),
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=notes__pb2.UpdateTaskRequest.FromString,
                    response_serializer=notes__pb2.Task.SerializeToString,
            ),
            'SummarizeRange': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeRange,
                    request_deserializer=notes__pb2.SummarizeRangeRequest.FromString,
                    response_serializer=notes__pb2.SummarizeRangeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notes.NotesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNoteFromAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/CreateNoteFromAudio',
            notes__pb2.CreateNoteFromAudioRequest.SerializeToString,
            notes__pb2.CreateNoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateNoteFromText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/CreateNoteFromText',
            notes__pb2.CreateNoteFromTextRequest.SerializeToString,
            notes__pb2.CreateNoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/GetNote',
            notes__pb2.GetNoteRequest.SerializeToString,
            notes__pb2.GetNoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListNotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/ListNotes',
            notes__pb2.ListNotesRequest.SerializeToString,
            notes__pb2.ListNotesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/ListTasks',
            notes__pb2.ListTasksRequest.SerializeToString,
            notes__pb2.ListTasksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/UpdateTask',
            notes__pb2.UpdateTaskRequest.SerializeToString,
            notes__pb2.Task.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SummarizeRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notes.NotesService/SummarizeRange',
            notes__pb2.SummarizeRangeRequest.SerializeToString,
            notes__pb2.SummarizeRangeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
